name: AstralEdit
version: 1.1.0
author: Shynixn
website: https://www.spigotmc.org/members/shynixn.63455/
main: com.github.shynixn.astraledit.bukkit.AstralEditPlugin
softdepend: [WorldEdit]
commands:
   awe:
      description: Opens the arena menu.
      usage: /<command>
      permission: astraledit.allowCommands
      permission-message: You don't have permission.